### PR TITLE
working on seeding script

### PR DESCRIPTION
**Pull request by janeslee**
please review the codes in seed.js. Few questions in my mind:

- should I define my headers in here? @Justin, I remember you saying it wouldn't be necessary. So I left it out for now but will def. trying importing a small set of data into my db to test. Will confirm.

- output.csv format is really ugly and hard to look at when everything is in one line when imported to google sheets. any recommendations to make it in more readable format?

### CODE REVIEW

**Comment by Siege211** [comment]
Looks good to me, but why only 1000 on the writeStream?

**Comment by janeslee** [comment]
@Siege211 That was just for testing purpose, definitely scaling it up to 10mil. Crossing fingers my laptop won't melt :p

**Comment by shakabandai** [comment]
@janeslee , for your two points
- re using headers with postgres, this may help https://gist.github.com/nepsilon/f2937fe10fe8b0efc0cc
- for changing the csv format to multiple lines/rows there are options from node, namely os.EOL, which formats the csv to your operating system => a script I used "fs.writeFileSync(filename, output.join(os.EOL))" taking out the os.EOL leaves it on one line; adding it puts each row separately which looks far nicer. check out the docs! https://nodejs.org/api/os.html

**Comment by shakabandai** [comment]
Also, https://popsql.io/learn-sql/postgresql/how-to-import-a-csv-in-postgresql/
Options for with/without headers

**Pull request merged**
